package:
  name: t2db_objects
  version: {{ GIT_DESCRIBE_TAG }}
source:
  git_url: ../
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
requirements:
  build:
    - python
    - setuptools
    - pymongo
    - pyyaml
  run:
    - python
    - setuptools
    - pymongo
    - pyyaml
test:
  source_files:
    - t2db_objects/tests
  requires:
    - pytest
  commands:
    - ls -la
    - pytest
about:
  home: https://github.com/ptorrestr/t2db_objects.git
  license: GPLv3
